In [47]:
import pandas as pd
import numpy as np
from openpyxl import load_workbook
from openpyxl.styles import Font, PatternFill, Alignment

# Lectura Base de datos

## Inspeccionando libro de Excel

In [13]:
xl = pd.ExcelFile('entrada\CLIENTES ANSATTV.xlsx')

In [15]:
xl.sheet_names

['CLIENTES NOROCCIDENTE', 'CLIENTES SAN ANTONIO']

In [ ]:
df_preview = pd.read_excel(xl, nrows=3)
df_preview

,CLIENTES NOROCCIDENTE,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,CI,CONTRATO,FECHA,Nombre del Usuario,PLAN,TELEFONO,DIRECCION,IP
1,1721701066,CON 0000534,2020-10-23 00:00:00,CARLOSAMA BERRONES MARCELINA MARIA,250 MB,0996503292,NANEGAL,10.0.68.12
2,1711017341,CON 0000537,2020-10-23 00:00:00,DEL HIERRO DIAZ DORIS AMANDA,250 MB,0996140633,NANEGAL,10.0.68.11

In [20]:
df_noroccidente = pd.read_excel(xl, sheet_name='CLIENTES NOROCCIDENTE', header=1)
df_noroccidente.head(2)

,CI,CONTRATO,FECHA,Nombre del Usuario,PLAN,TELEFONO,DIRECCION,IP
0,1721701066,CON 0000534,2020-10-23 00:00:00,CARLOSAMA BERRONES MARCELINA MARIA,250 MB,0996503292,NANEGAL,10.0.68.12
1,1711017341,CON 0000537,2020-10-23 00:00:00,DEL HIERRO DIAZ DORIS AMANDA,250 MB,0996140633,NANEGAL,10.0.68.11

In [21]:
df_noroccidente.shape

(487, 8)

In [22]:
df_noroccidente.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 487 entries, 0 to 486
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CI                  487 non-null    object
 1   CONTRATO            487 non-null    object
 2   FECHA               487 non-null    object
 3   Nombre del Usuario  487 non-null    object
 4   PLAN                487 non-null    object
 5   TELEFONO            487 non-null    object
 6   DIRECCION           486 non-null    object
 7   IP                  487 non-null    object
dtypes: object(8)
memory usage: 30.6+ KB

In [23]:
df_preview = pd.read_excel(xl, nrows=3, sheet_name='CLIENTES SAN ANTONIO')
df_preview

,CLIENTES ANSATTV,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,CI/RUC,#CONTRATO,FECHA,NOMBRE,PLAN,TELEFONO,DIRECCION,IP
1,1720998077,10391,2001-10-06 00:00:00,NaN,250Mbps,995698095,REINO DE QUITO Y SINCHOLAHUA,10.0.75.2
2,1713812251,00125,2015-08-27 00:00:00,NaN,250Mbps,995039097,PADRE RUMI 113 PB CONJ. TERRASOL,10.0.75.3

In [24]:
df_san_antonio = pd.read_excel(xl, sheet_name='CLIENTES SAN ANTONIO', header=1)
df_san_antonio.head(2)

,CI/RUC,#CONTRATO,FECHA,NOMBRE,PLAN,TELEFONO,DIRECCION,IP
0,1720998077,10391,2001-10-06,NaN,250Mbps,995698095,REINO DE QUITO Y SINCHOLAHUA,10.0.75.2
1,1713812251,125,2015-08-27,NaN,250Mbps,995039097,PADRE RUMI 113 PB CONJ. TERRASOL,10.0.75.3

In [25]:
df_san_antonio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 448 entries, 0 to 447
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CI/RUC     448 non-null    int64
 1   #CONTRATO  448 non-null    int64
 2   FECHA      448 non-null    datetime64[ns]
 3   NOMBRE     0 non-null      float64
 4   PLAN       448 non-null    object
 5   TELEFONO   448 non-null    object
 6   DIRECCION  448 non-null    object
 7   IP         448 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 28.1+ KB

## Noroccidente

In [32]:
df_noroccidente.shape

(487, 8)

In [26]:
df_noroccidente.isna().sum()

CI                    0
CONTRATO              0
FECHA                 0
Nombre del Usuario    0
PLAN                  0
TELEFONO              0
DIRECCION             1
IP                    0
dtype: int64

In [28]:
np.where(df_noroccidente.isna())

(array([216]), array([6]))

In [29]:
df_noroccidente.iloc[216]

CI                                              1726619636
CONTRATO                                       CON 0002466
FECHA                                  2022-10-04 00:00:00
Nombre del Usuario    DE LA TORRE CORTEZ MIREA MONSERRATH
PLAN                                                250 MB
TELEFONO                                        0962175803
DIRECCION                                              NaN
IP                                             10.0.53.150
Name: 216, dtype: object

In [36]:
conteo_contratos = df_noroccidente['CONTRATO'].value_counts()

In [37]:
contratos_repetidos = conteo_contratos[conteo_contratos > 1]

In [38]:
contratos_repetidos

CONTRATO
CON 0000919    2
Name: count, dtype: int64

In [42]:
df_noroccidente[ df_noroccidente['CONTRATO'].str.contains('CON 0000919') ]

,CI,CONTRATO,FECHA,Nombre del Usuario,PLAN,TELEFONO,DIRECCION,IP
11,1709646309,CON 0000919,2020-12-22 00:00:00,DEL HIERRO DIAZ JIMENA CECILIA,250 MB,0959800442,NANEGAL,10.0.68.65
269,1709646309,CON 0000919,2020-12-22 00:00:00,DEL HIERRO DIAZ JIMENA CECILIA,250 MB,0959800442,NANEGAL,10.0.68.64

Mismo contrato y cédula con direcciones IP **distintas**

In [43]:
contratos_duplicados = df_noroccidente[ df_noroccidente['CONTRATO'].str.contains('CON 0000919') ]

In [ ]:
with pd.ExcelWriter('Proc_noroccidente.xlsx', engine='openpyxl') as writer:
    contratos_duplicados.to_excel(writer, sheet_name='Duplicados_Contratos', index=False)

In [50]:
conteo_ci = df_noroccidente['CI'].value_counts()

In [51]:
ci_repeditos = conteo_ci[conteo_ci > 1]

In [52]:
ci_repeditos

CI
1760001040001    8
AAB296835        3
1715992010       2
1714342381       2
1712110079       2
0925603086       2
1705629002       2
1000665818       2
1704890373       2
1724809163       2
1720250925       2
1003049416       2
1713480208       2
1709646309       2
1720347531       2
0603090796       2
1712904653       2
1720023298       2
1711017341       2
1725986333       2
1723255335       2
Name: count, dtype: int64

In [53]:
len(ci_repeditos)

21

In [55]:
ci_repeditos.sum()

np.int64(49)

In [57]:
df_noroccidente[ df_noroccidente['CI'] == '1760001040001']

,CI,CONTRATO,FECHA,Nombre del Usuario,PLAN,TELEFONO,DIRECCION,IP
159,1760001040001,IDMINEDU_080,2024-04-29 00:00:00,ESCUELA MANUEL MATHEUS,300 MB,0996812939,NANEGAL,10.0.53.27
160,1760001040001,IDMINEDU_092,2024-05-01 00:00:00,ESCUELA ALONSO DE MERCADILLO,300 MB,0994383676,NANEGAL,10.0.60.118
161,1760001040001,IDMINEDU_096,2024-05-01 00:00:00,ESCUELA CARLOS RIVADENEIRA,300 MB,0985133533,NANEGAL,10.0.68.164
162,1760001040001,IDMINEDU_065,2024-05-01 00:00:00,ESCUELA FRANCISCO FALQUEZ AMPUERO,300 MB,0986667426,NANEGAL,10.0.60.205
163,1760001040001,IDMINEDU_094,2024-05-01 00:00:00,ESCUELA PATRICIO ROMERO BARBERIS,300 MB,0998048623,NANEGAL,10.0.60.193
164,1760001040001,IDMINEDU_095,2024-05-06 00:00:00,ESCUELA AMADO NERVO,300 MB,0983009670,NANEGAL,10.0.66.150
165,1760001040001,IDMINEDU_083,2024-05-06 00:00:00,ESCUELA RIO CENEPA,300 MB,0962902771,NANEGAL,10.0.66.29
166,1760001040001,IDMINEDU_093,2024-05-06 00:00:00,ESCUELA RIO UPANO,300 MB,0960958639,NANEGAL,10.0.66.95

In [61]:
for ci, cantidad in ci_repeditos.items():
    print (ci)

1760001040001
AAB296835
1715992010
1714342381
1712110079
0925603086
1705629002
1000665818
1704890373
1724809163
1720250925
1003049416
1713480208
1709646309
1720347531
0603090796
1712904653
1720023298
1711017341
1725986333
1723255335

números de cédulas repetidas

In [72]:
lista_registros_ci = []
for ci, cantidad in ci_repeditos.items():
    df_ci = df_noroccidente[df_noroccidente['CI'] == ci]
    lista_registros_ci.append(df_ci)

In [74]:
duplicados_ci = pd.concat(lista_registros_ci, ignore_index=True)

In [76]:
duplicados_ci.shape

(49, 8)

In [ ]:
with pd.ExcelWriter('Proc_noroccidente.xlsx', engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
    duplicados_ci.to_excel(writer, sheet_name='Duplicados_CI', index=False)

In [80]:
pd.pivot_table(
    df_noroccidente,
    values='CONTRATO',
    index='PLAN',
    aggfunc='count'
)

        CONTRATO
PLAN
250 MB       440
300 MB        34
350 MB        10
400 MB         1
450 MB         2

In [83]:
duplicados_ci.head(3)

,CI,CONTRATO,FECHA,Nombre del Usuario,PLAN,TELEFONO,DIRECCION,IP
0,1760001040001,IDMINEDU_080,2024-04-29 00:00:00,ESCUELA MANUEL MATHEUS,300 MB,0996812939,NANEGAL,10.0.53.27
1,1760001040001,IDMINEDU_092,2024-05-01 00:00:00,ESCUELA ALONSO DE MERCADILLO,300 MB,0994383676,NANEGAL,10.0.60.118
2,1760001040001,IDMINEDU_096,2024-05-01 00:00:00,ESCUELA CARLOS RIVADENEIRA,300 MB,0985133533,NANEGAL,10.0.68.164

In [82]:
pivot_completo = (duplicados_ci
    .groupby('CI')
    .agg(
        Contratos=('CONTRATO', 'count'),
        IPs=('IP', 'nunique'),
        Telefonos=('TELEFONO', 'nunique'),
        Nombres=('Nombre del Usuario', 'nunique')
    )
    .assign(
        Tipo_Duplicidad=lambda x: 
            np.where(x['Nombres'] > 1, 'Diferentes_nombres',
            np.where((x['IPs'] > 1) & (x['Telefonos'] == 1), 'Mismo_nombre_diferentes_IP',
            np.where((x['IPs'] == 1) & (x['Telefonos'] == 1), 'Registro_duplicado_identico',
            np.where((x['IPs'] > 1) & (x['Telefonos'] > 1), 'Multiples_IP_y_telefonos', 'Patron_mixto'))))
    )
    .sort_values('Contratos', ascending=False)
)

print(pivot_completo)

               Contratos  IPs  Telefonos  Nombres             Tipo_Duplicidad
CI
1760001040001          8    8          8        8          Diferentes_nombres
AAB296835              3    3          1        1  Mismo_nombre_diferentes_IP
1714342381             2    2          1        1  Mismo_nombre_diferentes_IP
1725986333             2    2          2        1    Multiples_IP_y_telefonos
1724809163             2    2          1        1  Mismo_nombre_diferentes_IP
1723255335             2    2          1        1  Mismo_nombre_diferentes_IP
1720347531             2    2          1        1  Mismo_nombre_diferentes_IP
1720250925             2    2          1        1  Mismo_nombre_diferentes_IP
1720023298             2    2          1        2          Diferentes_nombres
1715992010             2    2          2        2          Diferentes_nombres
0603090796             2    2          1        1  Mismo_nombre_diferentes_IP
0925603086             2    2          2        1    Multiples_IP_y_telefonos
1712904653             2    2          2        1    Multiples_IP_y_telefonos
1712110079             2    2          1        1  Mismo_nombre_diferentes_IP
1711017341             2    2          1        1  Mismo_nombre_diferentes_IP
1709646309             2    2          1        1  Mismo_nombre_diferentes_IP
1705629002             2    2          1        1  Mismo_nombre_diferentes_IP
1704890373             2    2          2        1    Multiples_IP_y_telefonos
1003049416             2    2          2        1    Multiples_IP_y_telefonos
1000665818             2    2          1        1  Mismo_nombre_diferentes_IP
1713480208             2    2          1        1  Mismo_nombre_diferentes_IP

In [ ]:
with pd.ExcelWriter('Proc_noroccidente.xlsx', mode='a', if_sheet_exists='replace', engine='openpyxl') as writer:
    pivot_completo.to_excel(writer, sheet_name='Duplicidad_CI', index=True)

In [90]:
df_noroccidente[ df_noroccidente['CI'] == '1720023298' ]

,CI,CONTRATO,FECHA,Nombre del Usuario,PLAN,TELEFONO,DIRECCION,IP
122,1720023298,CON 0003590,2023-06-14 00:00:00,ESCOBAR BARREROS DIEGO GIOVANY,250 MB,0998215192,NANEGAL,10.0.60.23
123,1720023298,CON 0003591,2023-06-14 00:00:00,ESCOBAR BARREROS DIEGO GIOVANY,250 MB,0998215192,NANEGAL,10.0.68.86

In [91]:
listado_ip = df_noroccidente['IP'].value_counts()

In [92]:
duplicados_ip = listado_ip[ listado_ip > 1 ]

In [93]:
duplicados_ip

Series([], Name: count, dtype: int64)

## San Antonio

In [94]:
df_san_antonio.shape

(448, 8)

In [103]:
df_san_antonio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 448 entries, 0 to 447
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CI/RUC     448 non-null    int64
 1   #CONTRATO  448 non-null    int64
 2   FECHA      448 non-null    datetime64[ns]
 3   NOMBRE     0 non-null      float64
 4   PLAN       448 non-null    object
 5   TELEFONO   448 non-null    object
 6   DIRECCION  448 non-null    object
 7   IP         448 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 28.1+ KB

In [95]:
df_san_antonio.isna().sum()

CI/RUC         0
#CONTRATO      0
FECHA          0
NOMBRE       448
PLAN           0
TELEFONO       0
DIRECCION      0
IP             0
dtype: int64

In [98]:
conteo_contratos_sa = df_san_antonio['#CONTRATO'].value_counts()

In [99]:
contratos_repetidos_sa = conteo_contratos_sa[conteo_contratos_sa > 1]

In [105]:
contratos_repetidos_sa

#CONTRATO
10397    2
1359     2
1460     2
Name: count, dtype: int64

In [106]:
df_san_antonio[ df_san_antonio['#CONTRATO'] == 10397 ]

,CI/RUC,#CONTRATO,FECHA,NOMBRE,PLAN,TELEFONO,DIRECCION,IP
199,1751517051,10397,2021-09-21,NaN,250Mbps,0995051106,SECTOR RAYOCUCHO,10.0.75.201
200,1751517051,10397,2021-09-21,NaN,250Mbps,995752651,REINO DE QUITO Y TWINZA,10.0.75.202

Mismo contrato y cédula con direcciones IP **distintas**

In [110]:
lista_contratos = []
for c, cantidad in contratos_repetidos_sa.items():
    df_c = df_san_antonio[df_san_antonio['#CONTRATO'] == c]
    lista_contratos.append(df_c)

In [111]:
duplicados_c = pd.concat(lista_contratos, ignore_index=True)

In [112]:
duplicados_c

,CI/RUC,#CONTRATO,FECHA,NOMBRE,PLAN,TELEFONO,DIRECCION,IP
0,1751517051,10397,2021-09-21,NaN,250Mbps,0995051106,SECTOR RAYOCUCHO,10.0.75.201
1,1751517051,10397,2021-09-21,NaN,250Mbps,995752651,REINO DE QUITO Y TWINZA,10.0.75.202
2,1712952991,1359,2021-05-19,NaN,250Mbps,0992803585,CONJUNTO TERRASOL,10.0.75.136
3,223654894,1359,2023-07-21,NaN,300Mbps,969003302,PULULAHUA Y SHEYGUA,10.0.77.120
4,1719188698,1460,2021-07-31,NaN,450Mbps,982618231,RAYOCUCHO,10.0.75.152
5,1724570831,1460,2021-08-12,NaN,250Mbps,989358148,RAYOCUCHO,10.0.75.157

In [113]:
with pd.ExcelWriter('Proc_san_antonio.xlsx', engine='openpyxl') as writer:
    duplicados_c.to_excel(writer, sheet_name='Duplicados_Contratos', index=False)

In [119]:
df_san_antonio.columns.values

array(['CI/RUC', '#CONTRATO', 'FECHA', 'NOMBRE', 'PLAN', 'TELEFONO',
       'DIRECCION', 'IP'], dtype=object)

In [120]:
conteo_ci_sa = df_san_antonio['CI/RUC'].value_counts()

In [121]:
ci_repeditos_sa = conteo_ci_sa[conteo_ci_sa > 1]

In [122]:
ci_repeditos_sa

CI/RUC
1716289200    3
1751517051    2
1751334127    2
1718896069    2
Name: count, dtype: int64

In [123]:
len(ci_repeditos_sa)

4

In [124]:
ci_repeditos_sa.sum()

np.int64(9)

números de cédulas repetidas

In [126]:
lista_registros_ci_sa = []
for ci, cantidad in ci_repeditos_sa.items():
    df_ci = df_san_antonio[df_san_antonio['CI/RUC'] == ci]
    lista_registros_ci_sa.append(df_ci)

In [127]:
duplicados_ci_sa = pd.concat(lista_registros_ci_sa, ignore_index=True)

In [128]:
duplicados_ci_sa.shape

(9, 8)

In [129]:
duplicados_ci_sa

,CI/RUC,#CONTRATO,FECHA,NOMBRE,PLAN,TELEFONO,DIRECCION,IP
0,1716289200,127779,2019-03-13,NaN,250Mbps,2396434,CASPIGASI,10.0.75.20
1,1716289200,423,2020-09-14,NaN,250Mbps,2396434,CASPIGASI,10.0.75.96
2,1716289200,1780,2021-09-11,NaN,250Mbps,2396434,CASPIGASI,10.0.75.185
3,1751517051,10397,2021-09-21,NaN,250Mbps,0995051106,SECTOR RAYOCUCHO,10.0.75.201
4,1751517051,10397,2021-09-21,NaN,250Mbps,995752651,REINO DE QUITO Y TWINZA,10.0.75.202
5,1751334127,476,2020-09-06,NaN,250Mbps,939459880,CHAVEZPAMBA,10.0.75.91
6,1751334127,478,2020-09-16,NaN,250Mbps,995183804,CHAVEZPAMBA,10.0.75.97
7,1718896069,6014,2023-04-27,NaN,250Mbps,993546374,REINO DE QUITO,10.0.77.86
8,1718896069,3315,2023-12-18,NaN,250Mbps,990051402,CALLE YACUÑAN Y ULTIMO PASAJE,10.0.77.168

In [130]:
with pd.ExcelWriter('Proc_san_antonio.xlsx', engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
    duplicados_ci_sa.to_excel(writer, sheet_name='Duplicados_CI', index=False)

In [132]:
pd.pivot_table(
    df_san_antonio,
    values='#CONTRATO',
    index='PLAN',
    aggfunc='count'
)

         #CONTRATO
PLAN
250Mbps        330
300Mbps         72
350Mbps         29
400Mbps          5
450Mbps         12

In [ ]:
duplicados_ci.head(3)

,CI,CONTRATO,FECHA,Nombre del Usuario,PLAN,TELEFONO,DIRECCION,IP
0,1760001040001,IDMINEDU_080,2024-04-29 00:00:00,ESCUELA MANUEL MATHEUS,300 MB,0996812939,NANEGAL,10.0.53.27
1,1760001040001,IDMINEDU_092,2024-05-01 00:00:00,ESCUELA ALONSO DE MERCADILLO,300 MB,0994383676,NANEGAL,10.0.60.118
2,1760001040001,IDMINEDU_096,2024-05-01 00:00:00,ESCUELA CARLOS RIVADENEIRA,300 MB,0985133533,NANEGAL,10.0.68.164

In [ ]:
pivot_completo = (duplicados_ci
    .groupby('CI')
    .agg(
        Contratos=('CONTRATO', 'count'),
        IPs=('IP', 'nunique'),
        Telefonos=('TELEFONO', 'nunique'),
        Nombres=('Nombre del Usuario', 'nunique')
    )
    .assign(
        Tipo_Duplicidad=lambda x: 
            np.where(x['Nombres'] > 1, 'Diferentes_nombres',
            np.where((x['IPs'] > 1) & (x['Telefonos'] == 1), 'Mismo_nombre_diferentes_IP',
            np.where((x['IPs'] == 1) & (x['Telefonos'] == 1), 'Registro_duplicado_identico',
            np.where((x['IPs'] > 1) & (x['Telefonos'] > 1), 'Multiples_IP_y_telefonos', 'Patron_mixto'))))
    )
    .sort_values('Contratos', ascending=False)
)

print(pivot_completo)

               Contratos  IPs  Telefonos  Nombres             Tipo_Duplicidad
CI
1760001040001          8    8          8        8          Diferentes_nombres
AAB296835              3    3          1        1  Mismo_nombre_diferentes_IP
1714342381             2    2          1        1  Mismo_nombre_diferentes_IP
1725986333             2    2          2        1    Multiples_IP_y_telefonos
1724809163             2    2          1        1  Mismo_nombre_diferentes_IP
1723255335             2    2          1        1  Mismo_nombre_diferentes_IP
1720347531             2    2          1        1  Mismo_nombre_diferentes_IP
1720250925             2    2          1        1  Mismo_nombre_diferentes_IP
1720023298             2    2          1        2          Diferentes_nombres
1715992010             2    2          2        2          Diferentes_nombres
0603090796             2    2          1        1  Mismo_nombre_diferentes_IP
0925603086             2    2          2        1    Multiples_IP_y_telefonos
1712904653             2    2          2        1    Multiples_IP_y_telefonos
1712110079             2    2          1        1  Mismo_nombre_diferentes_IP
1711017341             2    2          1        1  Mismo_nombre_diferentes_IP
1709646309             2    2          1        1  Mismo_nombre_diferentes_IP
1705629002             2    2          1        1  Mismo_nombre_diferentes_IP
1704890373             2    2          2        1    Multiples_IP_y_telefonos
1003049416             2    2          2        1    Multiples_IP_y_telefonos
1000665818             2    2          1        1  Mismo_nombre_diferentes_IP
1713480208             2    2          1        1  Mismo_nombre_diferentes_IP

In [ ]:
with pd.ExcelWriter('Proc_Empadronamiento.xlsx', mode='a', if_sheet_exists='replace', engine='openpyxl') as writer:
    pivot_completo.to_excel(writer, sheet_name='Duplicidad_CI', index=True)

In [ ]:
df_noroccidente[ df_noroccidente['CI'] == '1720023298' ]

,CI,CONTRATO,FECHA,Nombre del Usuario,PLAN,TELEFONO,DIRECCION,IP
122,1720023298,CON 0003590,2023-06-14 00:00:00,ESCOBAR BARREROS DIEGO GIOVANY,250 MB,0998215192,NANEGAL,10.0.60.23
123,1720023298,CON 0003591,2023-06-14 00:00:00,ESCOBAR BARREROS DIEGO GIOVANY,250 MB,0998215192,NANEGAL,10.0.68.86

In [ ]:
listado_ip = df_noroccidente['IP'].value_counts()

In [ ]:
duplicados_ip = listado_ip[ listado_ip > 1 ]

In [ ]:
duplicados_ip

Series([], Name: count, dtype: int64)